/* tslint:disable */
/* eslint-disable */
/**
 * API Pagos Instantáneos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface BankGetBanks
 */
export interface BankGetBanks {
    /**
     * Arreglo con listado de bancos.
     * @type {Array<BankGetBanksBanksInner>}
     * @memberof BankGetBanks
     */
    'banks': Array<BankGetBanksBanksInner>;
}
/**
 * Datos de banco.
 * @export
 * @interface BankGetBanksBanksInner
 */
export interface BankGetBanksBanksInner {
    /**
     * Identificador del banco.
     * @type {string}
     * @memberof BankGetBanksBanksInner
     */
    'bank_id': string;
    /**
     * Nombre del banco.
     * @type {string}
     * @memberof BankGetBanksBanksInner
     */
    'name': string;
    /**
     * Mensaje con particularidades del banco.
     * @type {string}
     * @memberof BankGetBanksBanksInner
     */
    'message': string;
    /**
     * Monto mínimo que acepta el banco en un pago.
     * @type {number}
     * @memberof BankGetBanksBanksInner
     */
    'min_amount': number;
    /**
     * Tipo de banco.
     * @type {string}
     * @memberof BankGetBanksBanksInner
     */
    'type': BankGetBanksBanksInnerTypeEnum;
    /**
     * Identificador del banco padre (si un banco tiene banca personas y empresas, el primero será el padre del segundo).
     * @type {string}
     * @memberof BankGetBanksBanksInner
     */
    'parent': string;
    /**
     * URL del logo del banco.
     * @type {string}
     * @memberof BankGetBanksBanksInner
     */
    'logo_url'?: string;
}

export const BankGetBanksBanksInnerTypeEnum = {
    Persona: 'Persona',
    Empresa: 'Empresa'
} as const;

export type BankGetBanksBanksInnerTypeEnum = typeof BankGetBanksBanksInnerTypeEnum[keyof typeof BankGetBanksBanksInnerTypeEnum];

/**
 * 
 * @export
 * @interface MerchantGetPaymentMethods
 */
export interface MerchantGetPaymentMethods {
    /**
     * Arreglo con métodos de pago disponibles.
     * @type {Array<MerchantGetPaymentMethodsPaymentMethodsInner>}
     * @memberof MerchantGetPaymentMethods
     */
    'paymentMethods': Array<MerchantGetPaymentMethodsPaymentMethodsInner>;
}
/**
 * Método de pago.
 * @export
 * @interface MerchantGetPaymentMethodsPaymentMethodsInner
 */
export interface MerchantGetPaymentMethodsPaymentMethodsInner {
    /**
     * Identificador del medio de pago.
     * @type {string}
     * @memberof MerchantGetPaymentMethodsPaymentMethodsInner
     */
    'id': string;
    /**
     * Nombre del medio de pago.
     * @type {string}
     * @memberof MerchantGetPaymentMethodsPaymentMethodsInner
     */
    'name': string;
    /**
     * URL del logo sugerido para mostrar.
     * @type {string}
     * @memberof MerchantGetPaymentMethodsPaymentMethodsInner
     */
    'logo_url': string;
}
/**
 * Información completa del pago. Datos con los que fue creado y el estado actual del pago.
 * @export
 * @interface PaymentGetPayment
 */
export interface PaymentGetPayment {
    /**
     * Identificador único del pago, es una cadena alfanumérica de 12 caracteres. Como este identificador es único, se puede usar, por ejemplo, para evitar procesar una notificación repetida. (Khipu espera un código 200 al notificar un pago, si esto no ocurre se reintenta hasta por dos días).
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'payment_id': string;
    /**
     * URL principal del pago, si el usuario no ha elegido previamente un método de pago se le muestran las opciones.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'payment_url': string;
    /**
     * URL de pago simplificado.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'simplified_transfer_url': string;
    /**
     * URL de pago normal.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'transfer_url': string;
    /**
     * URL para invocar el pago desde un dispositivo móvil usando la APP de Khipu.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'app_url': string;
    /**
     * Es `true` si el pago ya cuenta con todos los datos necesarios para abrir directamente la aplicación de pagos Khipu.
     * @type {boolean}
     * @memberof PaymentGetPayment
     */
    'ready_for_terminal': boolean;
    /**
     * Cadena de caracteres alfanuméricos que identifican unicamente al pago, es el identificador que el servidor de Khipu enviará al servidor del comercio cuando notifique que un pago está conciliado.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'notification_token': string;
    /**
     * Identificador único de una cuenta de cobro.
     * @type {number}
     * @memberof PaymentGetPayment
     */
    'receiver_id': number;
    /**
     * Fecha y hora de conciliación del pago. Formato ISO-8601.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'conciliation_date': string;
    /**
     * Motivo del pago.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'subject': string;
    /**
     * El monto del cobro.
     * @type {number}
     * @memberof PaymentGetPayment
     */
    'amount': number;
    /**
     * El código de moneda en formato ISO-4217.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'currency': string;
    /**
     * Estado del pago, puede ser `pending` (el pagador aún no comienza a pagar), `verifying` (se está verificando el pago) o `done`, cuando el pago ya está confirmado.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'status': PaymentGetPaymentStatusEnum;
    /**
     * Detalle del estado del pago: `pending` (el pagador aún no comienza a pagar), `normal` (el pago fue verificado y fue cancelado por algún medio de pago estándar), `marked-paid-by-receiver` (el cobrador marcó el cobro como pagado por otro medio), `rejected-by-payer` (el pagador declaró que no pagará), `marked-as-abuse` (el pagador declaró que no pagará y que el cobro fue no solicitado), y `reversed` (el pago fue anulado por el comercio, el dinero fue devuelto al pagador).
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'status_detail': PaymentGetPaymentStatusDetailEnum;
    /**
     * Detalle del cobro.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'body': string;
    /**
     * URL con imagen del cobro.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'picture_url': string;
    /**
     * URL del comprobante de pago.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'receipt_url': string;
    /**
     * URL donde se redirige al pagador luego que termina el pago.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'return_url': string;
    /**
     * URL donde se redirige al pagador luego de que desiste hacer el pago.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'cancel_url': string;
    /**
     * URL del webservice donde se notificará el pago.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'notify_url': string;
    /**
     * Versión de la API de notificación.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'notify_api_version': string;
    /**
     * Fecha máxima para ejecutar el pago (en formato ISO-8601). El cliente podrá realizar varios intentos de pago hasta dicha fecha. Cada intento tiene un plazo individual de 3 horas para su ejecución.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'expires_date': string;
    /**
     * Arreglo de URLs de archivos adjuntos al pago.
     * @type {Array<string>}
     * @memberof PaymentGetPayment
     */
    'attachment_urls': Array<string>;
    /**
     * Nombre del banco seleccionado por el pagador.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'bank': string;
    /**
     * Identificador del banco seleccionado por el pagador.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'bank_id': string;
    /**
     * Nombre del pagador.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'payer_name': string;
    /**
     * Correo electrónico del pagador.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'payer_email': string;
    /**
     * Identificador personal del pagador.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'personal_identifier': string;
    /**
     * Número de cuenta bancaria del pagador.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'bank_account_number': string;
    /**
     * Es `true` si la conciliación del pago fue hecha luego de la fecha de expiración.
     * @type {boolean}
     * @memberof PaymentGetPayment
     */
    'out_of_date_conciliation': boolean;
    /**
     * Identificador del pago asignado por el cobrador.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'transaction_id': string;
    /**
     * Campo genérico que asigna el cobrador al momento de hacer el pago.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'custom': string;
    /**
     * Correo electrónico de la persona responsable del pago.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'responsible_user_email': string;
    /**
     * Es `true` cuando este es un cobro por correo electrónico y Khipu enviará recordatorios.
     * @type {boolean}
     * @memberof PaymentGetPayment
     */
    'send_reminders': boolean;
    /**
     * Es `true` cuando Khipu enviará el cobro por correo electrónico.
     * @type {boolean}
     * @memberof PaymentGetPayment
     */
    'send_email': boolean;
    /**
     * Método de pago usado por el pagador, puede ser `regular_transfer` (transferencia normal) o `simplified_transfer` (transferencia simplificada).
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'payment_method': PaymentGetPaymentPaymentMethodEnum;
    /**
     * Origen de fondos usado por el pagador, puede ser `debit` para pago con débito, `prepaid` para pago con prepago, `credit` para pago con crédito, o vacío en el caso de que se haya pagado mediante transferencia bancaria.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'funds_source': PaymentGetPaymentFundsSourceEnum;
    /**
     * Monto a descontar del valor pagado.
     * @type {number}
     * @memberof PaymentGetPayment
     */
    'discount'?: number;
    /**
     * Ignorar este campo.
     * @type {string}
     * @memberof PaymentGetPayment
     */
    'third_party_authorization_details'?: string;
}

export const PaymentGetPaymentStatusEnum = {
    Pending: 'pending',
    Verifying: 'verifying',
    Done: 'done'
} as const;

export type PaymentGetPaymentStatusEnum = typeof PaymentGetPaymentStatusEnum[keyof typeof PaymentGetPaymentStatusEnum];
export const PaymentGetPaymentStatusDetailEnum = {
    Pending: 'pending',
    Normal: 'normal',
    MarkedPaidByReceiver: 'marked-paid-by-receiver',
    RejectedByPayer: 'rejected-by-payer',
    MarkedAsAbuse: 'marked-as-abuse',
    Reversed: 'reversed'
} as const;

export type PaymentGetPaymentStatusDetailEnum = typeof PaymentGetPaymentStatusDetailEnum[keyof typeof PaymentGetPaymentStatusDetailEnum];
export const PaymentGetPaymentPaymentMethodEnum = {
    RegularTransfer: 'regular_transfer',
    SimplifiedTransfer: 'simplified_transfer',
    NotAvailable: 'not_available'
} as const;

export type PaymentGetPaymentPaymentMethodEnum = typeof PaymentGetPaymentPaymentMethodEnum[keyof typeof PaymentGetPaymentPaymentMethodEnum];
export const PaymentGetPaymentFundsSourceEnum = {
    Debit: 'debit',
    Prepaid: 'prepaid',
    Credit: 'credit',
    NotAvailable: 'not-available',
    Empty: ''
} as const;

export type PaymentGetPaymentFundsSourceEnum = typeof PaymentGetPaymentFundsSourceEnum[keyof typeof PaymentGetPaymentFundsSourceEnum];

/**
 * Crea un pago en Khipu y obtiene las URLs para redirección al usuario para que complete el pago.
 * @export
 * @interface PaymentPostPayment
 */
export interface PaymentPostPayment {
    /**
     * El monto del cobro. Sin separador de miles y usando \'.\' como separador de decimales. Hasta 4 lugares decimales, dependiendo de la moneda.
     * @type {number}
     * @memberof PaymentPostPayment
     */
    'amount': number;
    /**
     * El código de moneda en formato ISO-4217.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'currency': PaymentPostPaymentCurrencyEnum;
    /**
     * Motivo.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'subject': string;
    /**
     * Identificador propio de la transacción. Ej: número de factura u orden de compra.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'transaction_id'?: string;
    /**
     * Parámetro para enviar información personalizada de la transacción. Ej: documento XML con el detalle del carro de compra.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'custom'?: string;
    /**
     * Descripción del cobro.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'body'?: string;
    /**
     * Identificador del banco para usar en el pago.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'bank_id'?: string;
    /**
     * La dirección URL a donde enviar al cliente mientras el pago está siendo verificado.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'return_url'?: string;
    /**
     * La dirección URL a donde enviar al cliente si decide no hacer hacer la transacción.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'cancel_url'?: string;
    /**
     * Una dirección URL de una foto de tu producto o servicio.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'picture_url'?: string;
    /**
     * La dirección del web-service que utilizará khipu para notificar cuando el pago esté conciliado.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'notify_url'?: string;
    /**
     * La dirección URL del archivo PDF con el contrato a firmar mediante este pago. El cobrador debe estar habilitado para este servicio y el campo `fixed_payer_personal_identifier` es obligatorio.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'contract_url'?: string;
    /**
     * Versión de la API de notificaciones para recibir avisos por web-service.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'notify_api_version'?: string;
    /**
     * Fecha máxima para ejecutar el pago (en formato ISO-8601). El cliente podrá realizar varios intentos de pago hasta dicha fecha. Cada intento tiene un plazo individual de 3 horas para su ejecución.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'expires_date'?: string;
    /**
     * Si es `true`, se enviará una solicitud de cobro al correo especificado en `payer_email`.
     * @type {boolean}
     * @memberof PaymentPostPayment
     */
    'send_email'?: boolean;
    /**
     * Nombre del pagador. Es obligatorio cuando `send_email` es `true`.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'payer_name'?: string;
    /**
     * Correo del pagador. Es obligatorio cuando `send_email` es `true`.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'payer_email'?: string;
    /**
     * Si es `true`, se enviarán recordatorios de cobro.
     * @type {boolean}
     * @memberof PaymentPostPayment
     */
    'send_reminders'?: boolean;
    /**
     * Correo electrónico del responsable de este cobro, debe corresponder a un usuario Khipu con permisos para cobrar usando esta cuenta de cobro.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'responsible_user_email'?: string;
    /**
     * Identificador personal. Si se especifica, solo podrá ser pagado usando ese identificador.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'fixed_payer_personal_identifier'?: string;
    /**
     * Comisión para el integrador. Sólo es válido si la cuenta de cobro tiene una cuenta de integrador asociada.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'integrator_fee'?: string;
    /**
     * Para cuentas de cobro con más cuenta propia. Permite elegir la cuenta donde debe ocurrir la transferencia.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'collect_account_uuid'?: string;
    /**
     * Fecha de rendición del cobro. Es también la fecha final para poder reembolsar el cobro. Formato ISO-8601.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'confirm_timeout_date'?: string;
    /**
     * El cobro sólo se podrá pagar utilizando el medio de pago especificado. Los posibles valores para este campo se encuentran en el campo `id` de la respuesta del endpoint `/api/3.0/merchants/paymentMethods`.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'mandatory_payment_method'?: string;
    /**
     * Nombre del comercio final para quien un proveedor de servicios de pago procesa un pago. Requerido para transacciones de clientes PSP; no aplicable para otros. En caso de tratarse de un PSP de PSP, estos deben ingresarse separados por \'->\'.
     * @type {string}
     * @memberof PaymentPostPayment
     */
    'psp_client_merchant_name'?: string;
}

export const PaymentPostPaymentCurrencyEnum = {
    Clp: 'CLP',
    Clf: 'CLF',
    Ars: 'ARS',
    Pen: 'PEN',
    Mxn: 'MXN',
    Usd: 'USD',
    Eur: 'EUR',
    Bob: 'BOB',
    Cop: 'COP'
} as const;

export type PaymentPostPaymentCurrencyEnum = typeof PaymentPostPaymentCurrencyEnum[keyof typeof PaymentPostPaymentCurrencyEnum];

/**
 * Crea un pago en Khipu y obtiene las URLs para redirección al usuario para que complete el pago.
 * @export
 * @interface PaymentPostPayment2
 */
export interface PaymentPostPayment2 {
    /**
     * Identificador único del pago, es una cadena alfanumérica de 12 caracteres. Como este identificador es único, se puede usar, por ejemplo, para evitar procesar una notificación repetida. (Khipu espera un código 200 al notificar un pago, si esto no ocurre se reintenta hasta por dos días).
     * @type {string}
     * @memberof PaymentPostPayment2
     */
    'payment_id': string;
    /**
     * URL principal del pago, si el usuario no ha elegido previamente un método de pago se le muestran las opciones.
     * @type {string}
     * @memberof PaymentPostPayment2
     */
    'payment_url': string;
    /**
     * URL de pago simplificado.
     * @type {string}
     * @memberof PaymentPostPayment2
     */
    'simplified_transfer_url': string;
    /**
     * URL de pago normal.
     * @type {string}
     * @memberof PaymentPostPayment2
     */
    'transfer_url': string;
    /**
     * URL para invocar el pago desde un dispositivo móvil usando la APP de Khipu.
     * @type {string}
     * @memberof PaymentPostPayment2
     */
    'app_url': string;
    /**
     * Es `true` si el pago ya cuenta con todos los datos necesarios para abrir directamente la aplicación de pagos Khipu.
     * @type {boolean}
     * @memberof PaymentPostPayment2
     */
    'ready_for_terminal': boolean;
}
/**
 * Reembolsa total o parcialmente el monto de un pago. Esta operación solo se puede realizar en los comercios que recauden en cuenta Khipu y antes de la rendición de los fondos correspondientes.
 * @export
 * @interface PaymentPostPaymentRefunds
 */
export interface PaymentPostPaymentRefunds {
    /**
     * El monto a devolver. Sin separador de miles y usando \'.\' como separador de decimales. Hasta 4 lugares decimales, dependiendo de la moneda. Si se omite el reembolso se hará por el total del monto del pago.
     * @type {number}
     * @memberof PaymentPostPaymentRefunds
     */
    'amount'?: number;
}
/**
 * Predicción acerca del resultado de un pago, si podrá o no funcionar. Información adicional como máximo posible de transferir a un nuevo destinatario.
 * @export
 * @interface PredictGetPredict
 */
export interface PredictGetPredict {
    /**
     * El resultado de la predicción.
     * @type {string}
     * @memberof PredictGetPredict
     */
    'result': PredictGetPredictResultEnum;
    /**
     * El monto máximo posible para transferir.
     * @type {number}
     * @memberof PredictGetPredict
     */
    'max_amount': number;
    /**
     * Fecha de término para la restricción de monto en formato ISO-8601
     * @type {string}
     * @memberof PredictGetPredict
     */
    'cool_down_date': string;
    /**
     * Monto máximo para transferir a un nuevo destinatario.
     * @type {number}
     * @memberof PredictGetPredict
     */
    'new_destinatary_max_amount': number;
}

export const PredictGetPredictResultEnum = {
    Ok: 'ok',
    NewDestinataryAmountExceeded: 'new_destinatary_amount_exceeded',
    MaxAmountExceeded: 'max_amount_exceeded',
    NewDestinataryCoolDown: 'new_destinatary_cool_down',
    NotAvailableAccount: 'not_available_account'
} as const;

export type PredictGetPredictResultEnum = typeof PredictGetPredictResultEnum[keyof typeof PredictGetPredictResultEnum];

/**
 * Crear una nueva cuenta de cobro asociada a un integrador. Necesita datos de la cuenta de usuario asociada, datos de facturación y datos de contacto.
 * @export
 * @interface ReceiverPostReceiver
 */
export interface ReceiverPostReceiver {
    /**
     * Nombre de pila del administrador de la cuenta de cobro a crear.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'admin_first_name': string;
    /**
     * Apellido del administrador de la cuenta de cobro a crear.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'admin_last_name': string;
    /**
     * Correo electrónico del administrador de la cuenta de cobro a crear.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'admin_email': string;
    /**
     * Código alfanumérico de dos caracteres ISO 3166-1 del país de la cuenta de cobro a crear.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'country_code': string;
    /**
     * Identificador tributario del cobrador asociado a la cuenta de cobro a crear.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'business_identifier': string;
    /**
     * Categoría tributaria o rubro tributario del cobrador asociado a la cuenta de cobro a crear.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'business_category': string;
    /**
     * Nombre tributario del cobrador asociado a la cuenta de cobro a crear.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'business_name': string;
    /**
     * Teléfono del cobrador asociado a la cuenta de cobro a crear.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'business_phone': string;
    /**
     * Dirección del cobrador de la cuenta de cobro a crear.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'business_address_line_1': string;
    /**
     * Segunda línea de la dirección del cobrador de la cuenta de cobro a crear.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'business_address_line_2': string;
    /**
     * Tercera línea de la dirección del cobrador de la cuenta de cobro a crear.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'business_address_line_3': string;
    /**
     * Nombre del contacto del cobrador.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'contact_full_name': string;
    /**
     * Cargo del contacto del cobrador.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'contact_job_title': string;
    /**
     * Correo electrónico del contacto del cobrador.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'contact_email': string;
    /**
     * Teléfono del contacto del cobrador.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'contact_phone': string;
    /**
     * Identificador del banco.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'bank_account_bank_id'?: string;
    /**
     * Tipo de cuenta. Es obligatorio si se utiliza el modelo alternativo de integrador de confianza.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'bank_account_type'?: string;
    /**
     * Identificador personal del dueño de la cuenta de banco.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'bank_account_identifier'?: string;
    /**
     * Nombre de la cuenta de banco.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'bank_account_name'?: string;
    /**
     * Número de la cuenta en el banco.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'bank_account_number'?: string;
    /**
     * URL por omisión para el webservice donde se notificará el pago.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'notify_url'?: string;
    /**
     * URL para el webservice donde se notificará la rendición.
     * @type {string}
     * @memberof ReceiverPostReceiver
     */
    'rendition_url'?: string;
}
/**
 * Objeto para respuesta de creación de cuenta de cobro.
 * @export
 * @interface ReceiverPostReceiver2
 */
export interface ReceiverPostReceiver2 {
    /**
     * Identificador único de la cuenta de cobro.
     * @type {string}
     * @memberof ReceiverPostReceiver2
     */
    'receiver_id': string;
    /**
     * Llave secreta de la cuenta de cobro, se usa para firmar todas las peticiones.
     * @type {string}
     * @memberof ReceiverPostReceiver2
     */
    'secret': string;
}
/**
 * Objeto para respuestas exitosas de la API.
 * @export
 * @interface Success
 */
export interface Success {
    /**
     * Mensaje a desplegar al usuario.
     * @type {string}
     * @memberof Success
     */
    'message': string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Borrar un pago. Solo se pueden borrar pagos que estén pendientes de pagar. Esta operación no puede deshacerse.
         * @summary Delete payment by Id
         * @param {string} id Identificador del pago
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePaymentById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletePaymentById', 'id', id)
            const localVarPath = `/v3/payments/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Este método obtiene la lista de bancos que se pueden utilizar para pagar en esta cuenta de cobro.
         * @summary Get banks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBanks: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v3/banks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Obtiene el listado de medios de pago disponible para una cuenta de cobrador.
         * @summary Get payment methods
         * @param {number} id Identificador de la cuenta de cobro
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMerchantPaymentMethodsById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getMerchantPaymentMethodsById', 'id', id)
            const localVarPath = `/v3/merchants/{id}/paymentMethods`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Información completa del pago. Datos con los que fue creado y el estado actual del pago.
         * @summary Get payment by Id
         * @param {string} id Identificador del pago
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPaymentById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getPaymentById', 'id', id)
            const localVarPath = `/v3/payments/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Predicción acerca del resultado de un pago, si podrá o no funcionar. Información adicional como máximo posible de transferir a un nuevo destinatario.
         * @summary Get payment prediction
         * @param {string} payerEmail Correo electrónico del pagador
         * @param {string} bankId Identificador del banco de origen
         * @param {string} amount Monto del pago
         * @param {string} currency Moneda en formato ISO-4217
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPredict: async (payerEmail: string, bankId: string, amount: string, currency: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'payerEmail' is not null or undefined
            assertParamExists('getPredict', 'payerEmail', payerEmail)
            // verify required parameter 'bankId' is not null or undefined
            assertParamExists('getPredict', 'bankId', bankId)
            // verify required parameter 'amount' is not null or undefined
            assertParamExists('getPredict', 'amount', amount)
            // verify required parameter 'currency' is not null or undefined
            assertParamExists('getPredict', 'currency', currency)
            const localVarPath = `/v3/predict`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            if (payerEmail !== undefined) {
                localVarQueryParameter['payer_email'] = payerEmail;
            }

            if (bankId !== undefined) {
                localVarQueryParameter['bank_id'] = bankId;
            }

            if (amount !== undefined) {
                localVarQueryParameter['amount'] = amount;
            }

            if (currency !== undefined) {
                localVarQueryParameter['currency'] = currency;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Crea un pago en Khipu y obtiene las URLs para redirección al usuario para que complete el pago.
         * @summary Create payment
         * @param {PaymentPostPayment} [paymentPostPayment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postPayment: async (paymentPostPayment?: PaymentPostPayment, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v3/payments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(paymentPostPayment, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * **Advertencia: Esta función sólo está disponible para los clientes que la hayan contratado de forma independiente. Para utilizarla, póngase en contacto con nosotros en soporte@khipu.com**<br><br> Confirmar el pago. Al confirmar el pago, este será rendido al día hábil siguiente. 
         * @summary Confirm payment by Id
         * @param {string} id Identificador del pago
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postPaymentConfirmById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('postPaymentConfirmById', 'id', id)
            const localVarPath = `/v3/payments/{id}/confirm`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Reembolsa total o parcialmente el monto de un pago. Esta operación solo se puede realizar en los comercios que recauden en cuenta Khipu y antes de la rendición de los fondos correspondientes.
         * @summary Refund payment by Id
         * @param {string} id Identificador del pago
         * @param {PaymentPostPaymentRefunds} [paymentPostPaymentRefunds] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postPaymentRefundsById: async (id: string, paymentPostPaymentRefunds?: PaymentPostPaymentRefunds, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('postPaymentRefundsById', 'id', id)
            const localVarPath = `/v3/payments/{id}/refunds`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(paymentPostPaymentRefunds, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * **Advertencia: Esta función sólo está disponible para los clientes que la hayan contratado de forma independiente. Para utilizarla, póngase en contacto con nosotros en soporte@khipu.com**<br><br> Crear una nueva cuenta de cobro asociada a un integrador. Necesita datos de la cuenta de usuario asociada, datos de facturación y datos de contacto. 
         * @summary Post receiver
         * @param {ReceiverPostReceiver} [receiverPostReceiver] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postReceiver: async (receiverPostReceiver?: ReceiverPostReceiver, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v3/receivers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(receiverPostReceiver, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Borrar un pago. Solo se pueden borrar pagos que estén pendientes de pagar. Esta operación no puede deshacerse.
         * @summary Delete payment by Id
         * @param {string} id Identificador del pago
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePaymentById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Success>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePaymentById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deletePaymentById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Este método obtiene la lista de bancos que se pueden utilizar para pagar en esta cuenta de cobro.
         * @summary Get banks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBanks(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BankGetBanks>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBanks(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getBanks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Obtiene el listado de medios de pago disponible para una cuenta de cobrador.
         * @summary Get payment methods
         * @param {number} id Identificador de la cuenta de cobro
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMerchantPaymentMethodsById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MerchantGetPaymentMethods>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMerchantPaymentMethodsById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getMerchantPaymentMethodsById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Información completa del pago. Datos con los que fue creado y el estado actual del pago.
         * @summary Get payment by Id
         * @param {string} id Identificador del pago
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPaymentById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentGetPayment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPaymentById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getPaymentById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Predicción acerca del resultado de un pago, si podrá o no funcionar. Información adicional como máximo posible de transferir a un nuevo destinatario.
         * @summary Get payment prediction
         * @param {string} payerEmail Correo electrónico del pagador
         * @param {string} bankId Identificador del banco de origen
         * @param {string} amount Monto del pago
         * @param {string} currency Moneda en formato ISO-4217
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPredict(payerEmail: string, bankId: string, amount: string, currency: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PredictGetPredict>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPredict(payerEmail, bankId, amount, currency, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getPredict']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Crea un pago en Khipu y obtiene las URLs para redirección al usuario para que complete el pago.
         * @summary Create payment
         * @param {PaymentPostPayment} [paymentPostPayment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postPayment(paymentPostPayment?: PaymentPostPayment, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentPostPayment2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postPayment(paymentPostPayment, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.postPayment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * **Advertencia: Esta función sólo está disponible para los clientes que la hayan contratado de forma independiente. Para utilizarla, póngase en contacto con nosotros en soporte@khipu.com**<br><br> Confirmar el pago. Al confirmar el pago, este será rendido al día hábil siguiente. 
         * @summary Confirm payment by Id
         * @param {string} id Identificador del pago
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postPaymentConfirmById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Success>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postPaymentConfirmById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.postPaymentConfirmById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Reembolsa total o parcialmente el monto de un pago. Esta operación solo se puede realizar en los comercios que recauden en cuenta Khipu y antes de la rendición de los fondos correspondientes.
         * @summary Refund payment by Id
         * @param {string} id Identificador del pago
         * @param {PaymentPostPaymentRefunds} [paymentPostPaymentRefunds] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postPaymentRefundsById(id: string, paymentPostPaymentRefunds?: PaymentPostPaymentRefunds, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Success>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postPaymentRefundsById(id, paymentPostPaymentRefunds, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.postPaymentRefundsById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * **Advertencia: Esta función sólo está disponible para los clientes que la hayan contratado de forma independiente. Para utilizarla, póngase en contacto con nosotros en soporte@khipu.com**<br><br> Crear una nueva cuenta de cobro asociada a un integrador. Necesita datos de la cuenta de usuario asociada, datos de facturación y datos de contacto. 
         * @summary Post receiver
         * @param {ReceiverPostReceiver} [receiverPostReceiver] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postReceiver(receiverPostReceiver?: ReceiverPostReceiver, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReceiverPostReceiver2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postReceiver(receiverPostReceiver, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.postReceiver']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Borrar un pago. Solo se pueden borrar pagos que estén pendientes de pagar. Esta operación no puede deshacerse.
         * @summary Delete payment by Id
         * @param {string} id Identificador del pago
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePaymentById(id: string, options?: RawAxiosRequestConfig): AxiosPromise<Success> {
            return localVarFp.deletePaymentById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Este método obtiene la lista de bancos que se pueden utilizar para pagar en esta cuenta de cobro.
         * @summary Get banks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBanks(options?: RawAxiosRequestConfig): AxiosPromise<BankGetBanks> {
            return localVarFp.getBanks(options).then((request) => request(axios, basePath));
        },
        /**
         * Obtiene el listado de medios de pago disponible para una cuenta de cobrador.
         * @summary Get payment methods
         * @param {number} id Identificador de la cuenta de cobro
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMerchantPaymentMethodsById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<MerchantGetPaymentMethods> {
            return localVarFp.getMerchantPaymentMethodsById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Información completa del pago. Datos con los que fue creado y el estado actual del pago.
         * @summary Get payment by Id
         * @param {string} id Identificador del pago
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPaymentById(id: string, options?: RawAxiosRequestConfig): AxiosPromise<PaymentGetPayment> {
            return localVarFp.getPaymentById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Predicción acerca del resultado de un pago, si podrá o no funcionar. Información adicional como máximo posible de transferir a un nuevo destinatario.
         * @summary Get payment prediction
         * @param {string} payerEmail Correo electrónico del pagador
         * @param {string} bankId Identificador del banco de origen
         * @param {string} amount Monto del pago
         * @param {string} currency Moneda en formato ISO-4217
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPredict(payerEmail: string, bankId: string, amount: string, currency: string, options?: RawAxiosRequestConfig): AxiosPromise<PredictGetPredict> {
            return localVarFp.getPredict(payerEmail, bankId, amount, currency, options).then((request) => request(axios, basePath));
        },
        /**
         * Crea un pago en Khipu y obtiene las URLs para redirección al usuario para que complete el pago.
         * @summary Create payment
         * @param {PaymentPostPayment} [paymentPostPayment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postPayment(paymentPostPayment?: PaymentPostPayment, options?: RawAxiosRequestConfig): AxiosPromise<PaymentPostPayment2> {
            return localVarFp.postPayment(paymentPostPayment, options).then((request) => request(axios, basePath));
        },
        /**
         * **Advertencia: Esta función sólo está disponible para los clientes que la hayan contratado de forma independiente. Para utilizarla, póngase en contacto con nosotros en soporte@khipu.com**<br><br> Confirmar el pago. Al confirmar el pago, este será rendido al día hábil siguiente. 
         * @summary Confirm payment by Id
         * @param {string} id Identificador del pago
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postPaymentConfirmById(id: string, options?: RawAxiosRequestConfig): AxiosPromise<Success> {
            return localVarFp.postPaymentConfirmById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Reembolsa total o parcialmente el monto de un pago. Esta operación solo se puede realizar en los comercios que recauden en cuenta Khipu y antes de la rendición de los fondos correspondientes.
         * @summary Refund payment by Id
         * @param {string} id Identificador del pago
         * @param {PaymentPostPaymentRefunds} [paymentPostPaymentRefunds] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postPaymentRefundsById(id: string, paymentPostPaymentRefunds?: PaymentPostPaymentRefunds, options?: RawAxiosRequestConfig): AxiosPromise<Success> {
            return localVarFp.postPaymentRefundsById(id, paymentPostPaymentRefunds, options).then((request) => request(axios, basePath));
        },
        /**
         * **Advertencia: Esta función sólo está disponible para los clientes que la hayan contratado de forma independiente. Para utilizarla, póngase en contacto con nosotros en soporte@khipu.com**<br><br> Crear una nueva cuenta de cobro asociada a un integrador. Necesita datos de la cuenta de usuario asociada, datos de facturación y datos de contacto. 
         * @summary Post receiver
         * @param {ReceiverPostReceiver} [receiverPostReceiver] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postReceiver(receiverPostReceiver?: ReceiverPostReceiver, options?: RawAxiosRequestConfig): AxiosPromise<ReceiverPostReceiver2> {
            return localVarFp.postReceiver(receiverPostReceiver, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Borrar un pago. Solo se pueden borrar pagos que estén pendientes de pagar. Esta operación no puede deshacerse.
     * @summary Delete payment by Id
     * @param {string} id Identificador del pago
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deletePaymentById(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deletePaymentById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Este método obtiene la lista de bancos que se pueden utilizar para pagar en esta cuenta de cobro.
     * @summary Get banks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getBanks(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getBanks(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Obtiene el listado de medios de pago disponible para una cuenta de cobrador.
     * @summary Get payment methods
     * @param {number} id Identificador de la cuenta de cobro
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getMerchantPaymentMethodsById(id: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getMerchantPaymentMethodsById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Información completa del pago. Datos con los que fue creado y el estado actual del pago.
     * @summary Get payment by Id
     * @param {string} id Identificador del pago
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getPaymentById(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getPaymentById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Predicción acerca del resultado de un pago, si podrá o no funcionar. Información adicional como máximo posible de transferir a un nuevo destinatario.
     * @summary Get payment prediction
     * @param {string} payerEmail Correo electrónico del pagador
     * @param {string} bankId Identificador del banco de origen
     * @param {string} amount Monto del pago
     * @param {string} currency Moneda en formato ISO-4217
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getPredict(payerEmail: string, bankId: string, amount: string, currency: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getPredict(payerEmail, bankId, amount, currency, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Crea un pago en Khipu y obtiene las URLs para redirección al usuario para que complete el pago.
     * @summary Create payment
     * @param {PaymentPostPayment} [paymentPostPayment] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postPayment(paymentPostPayment?: PaymentPostPayment, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postPayment(paymentPostPayment, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * **Advertencia: Esta función sólo está disponible para los clientes que la hayan contratado de forma independiente. Para utilizarla, póngase en contacto con nosotros en soporte@khipu.com**<br><br> Confirmar el pago. Al confirmar el pago, este será rendido al día hábil siguiente. 
     * @summary Confirm payment by Id
     * @param {string} id Identificador del pago
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postPaymentConfirmById(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postPaymentConfirmById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Reembolsa total o parcialmente el monto de un pago. Esta operación solo se puede realizar en los comercios que recauden en cuenta Khipu y antes de la rendición de los fondos correspondientes.
     * @summary Refund payment by Id
     * @param {string} id Identificador del pago
     * @param {PaymentPostPaymentRefunds} [paymentPostPaymentRefunds] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postPaymentRefundsById(id: string, paymentPostPaymentRefunds?: PaymentPostPaymentRefunds, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postPaymentRefundsById(id, paymentPostPaymentRefunds, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * **Advertencia: Esta función sólo está disponible para los clientes que la hayan contratado de forma independiente. Para utilizarla, póngase en contacto con nosotros en soporte@khipu.com**<br><br> Crear una nueva cuenta de cobro asociada a un integrador. Necesita datos de la cuenta de usuario asociada, datos de facturación y datos de contacto. 
     * @summary Post receiver
     * @param {ReceiverPostReceiver} [receiverPostReceiver] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postReceiver(receiverPostReceiver?: ReceiverPostReceiver, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postReceiver(receiverPostReceiver, options).then((request) => request(this.axios, this.basePath));
    }
}



